---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    virtlet.cloud: ""
  name: virtletimagemappings.virtlet.k8s
spec:
  group: virtlet.k8s
  names:
    kind: VirtletImageMapping
    plural: virtletimagemappings
    shortNames:
    - vim
    singular: virtletimagemapping
  scope: Namespaced
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    virtlet.cloud: ""
  name: virtletconfigmappings.virtlet.k8s
spec:
  group: virtlet.k8s
  names:
    kind: VirtletConfigMapping
    plural: virtletconfigmappings
    shortNames:
    - vcm
    singular: virtletconfigmapping
  scope: Namespaced
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null

